import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Real or AI Image Detector | RealOrAIImage.com",
  description: "Instantly detect whether an image is a real camera photograph or AI-generated by Midjourney, DALL-E 3, Stable Diffusion, or Flux using Gemini AI Vision.",
  keywords: ["AI detector", "Real or AI image", "Deepfake detector", "Midjourney detector", "DALL-E detector", "Gemini AI Vision"],
  openGraph: {
    title: "Real or AI Image Detector",
    description: "AI-powered forensic analysis to detect synthetic and AI-generated images.",
    url: "https://realoraiimage.com",
    siteName: "RealOrAIImage",
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="antialiased bg-[#090d16] text-slate-100 selection:bg-purple-500 selection:text-white">
        {children}
      </body>
    </html>
  );
}
