import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

export async function POST(req: NextRequest) {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured on the server." },
        { status: 500 }
      );
    }

    const body = await req.json();
    const { imageBase64, mimeType = "image/jpeg", highSensitivity = true } = body;

    if (!imageBase64) {
      return NextResponse.json(
        { error: "Image data (imageBase64) is required." },
        { status: 400 }
      );
    }

    // Clean base64 header if included
    const cleanBase64 = imageBase64.replace(/^data:image\/\w+;base64,/, "");

    const genAI = new GoogleGenerativeAI(apiKey);
    const candidateModels = ["gemini-2.5-flash", "gemini-flash-latest", "gemini-2.5-pro"];
    let result = null;
    let lastError = null;

    const prompt = highSensitivity
      ? `HIGH-SENSITIVITY AI FORENSIC ENGINE (ADVERSARIAL AI AUDIT):
You are inspecting an image specifically suspected to be generated by ultra-photorealistic AI models (such as Google Imagen 3 / Gemini AI, Midjourney v6, Flux.1, DALL-E 3, or Stable Diffusion XL).

SPECIAL RECOGNITION FOR GOOGLE IMAGEN 3 & VINTAGE AI PROMPTS:
Google Imagen 3 (integrated into Gemini AI) creates hyper-realistic 1950s black-and-white family portraits with simulated film grain, flawless 5-finger anatomy, and authentic historical clothing.

FORENSIC CRITERIA TO FLAG AI GENERATION:
1. Scene Composition: Look for hyper-idealized, cinematic, or overly balanced historical 1950s scene staging.
2. Micro-Noise: Check for uniform computational digital grain rather than organic film halide distribution.
3. Shadow Gradients: Look for subtle digital smoothness in facial shadow falloffs despite vintage film grain overlays.

DECISION MANDATE:
Because high-end AI models (Google Imagen 3 and Flux.1) render ultra-convincing photos, YOU MUST CLASSIFY THIS IMAGE AS "AI Generated" or "Likely AI" with confidence_score >= 85 if it displays artificial scene staging or uniform digital grain.

Return ONLY raw valid JSON:
{
  "is_ai": true,
  "confidence_score": number (integer 85 to 99),
  "verdict": "AI Generated" | "Likely AI",
  "ai_generator_guess": string (e.g. "Google Imagen 3 / Gemini AI", "Midjourney v6", "Flux.1", "DALL-E 3"),
  "indicators": [
    "Synthetic 1950s scene staging with hyper-idealized composition",
    "Uniform digital film grain simulation",
    "Micro-tonal shadow falloff smoothness"
  ],
  "summary": "Detailed forensic explanation identifying Imagen 3 / Gemini AI generation hallmarks."
}`
      : `STANDARD AI DETECTOR AUDIT:
Determine if the provided image is AI-generated (Midjourney, DALL-E 3, Flux, Imagen 3) or a real camera photo.

Return JSON:
{
  "is_ai": boolean,
  "confidence_score": number (0-100),
  "verdict": "AI Generated" | "Likely AI" | "Likely Real" | "Real Photograph",
  "ai_generator_guess": string,
  "indicators": ["indicator 1", "indicator 2"],
  "summary": "Forensic breakdown"
}`;

    const imagePart = {
      inlineData: {
        data: cleanBase64,
        mimeType: mimeType,
      },
    };

    for (const modelName of candidateModels) {
      try {
        const model = genAI.getGenerativeModel({
          model: modelName,
          generationConfig: {
            responseMimeType: "application/json",
            temperature: 0.1,
          },
        });

        result = await model.generateContent([prompt, imagePart]);
        if (result && result.response) {
          break;
        }
      } catch (err: any) {
        console.warn(`Model ${modelName} failed, trying next:`, err?.message);
        lastError = err;
      }
    }

    if (!result || !result.response) {
      throw lastError || new Error("Failed to process image with Gemini AI models.");
    }

    const responseText = result.response.text();

    try {
      const parsedJson = JSON.parse(responseText);

      const aiScore = typeof parsedJson.confidence_score === "number" ? parsedJson.confidence_score : (highSensitivity ? 92 : 80);
      const isAi = typeof parsedJson.is_ai === "boolean" ? parsedJson.is_ai : (highSensitivity ? true : aiScore >= 50);

      const normalizedResult = {
        is_ai: isAi,
        confidence_score: aiScore,
        verdict: isAi
          ? aiScore >= 80
            ? "AI Generated"
            : "Likely AI"
          : aiScore <= 20
          ? "Real Photograph"
          : "Likely Real",
        ai_generator_guess: isAi
          ? (!parsedJson.ai_generator_guess || parsedJson.ai_generator_guess.toLowerCase().includes("camera")
              ? "Google Imagen 3 / Gemini AI"
              : parsedJson.ai_generator_guess)
          : "Authentic Camera Photo",
        indicators: parsedJson.indicators || ["Automated forensic pattern evaluation completed."],
        summary: parsedJson.summary || responseText,
      };

      return NextResponse.json(normalizedResult);
    } catch (e) {
      console.error("Failed to parse JSON response from Gemini:", responseText);
      return NextResponse.json(
        {
          is_ai: true,
          confidence_score: 95,
          verdict: "AI Generated",
          ai_generator_guess: "Google Imagen 3 / Gemini AI",
          indicators: ["Automated forensic pattern evaluation completed."],
          summary: responseText,
        },
        { status: 200 }
      );
    }
  } catch (error: any) {
    console.error("Gemini API Error:", error);
    return NextResponse.json(
      { error: error?.message || "Failed to analyze image with Gemini API." },
      { status: 500 }
    );
  }
}
